### ISSUE TITLE
Templates rather than interactive init

### ISSUE THREAD

**Issue by kootenpv** [sdispater/poet#3]
I was hoping `init` would fill in more for me :) It's probably still part of your plan. 

I think (for now) that it would be faster/nicer when I would just copy your example from the README and start editing the things to how it should be for me.

Granted, the filling in of folder/package name and github info is a really nice addition, but maybe that could be incorporated during the creation of a personalized template.

Perhaps you could make templates so that it could be inited faster?

Another idea would be to work with submodules, too.

    poet init basic pyup travis tox gitignore pypi pypi-dev MIT

where each would have some default settings. Maybe a submodule would be a different section in the toml?

Similarly, `poet init full` could just give everything available; sometimes it is easier to just remove the things not needed :)

Yet another idea: my projects are probably going to be similar to each other (more similar than my project vs your projects). It would be nice if poet would enable me to create a template myself or something, or inherit from another project. Maybe a submodule structure would work instead.

**Comment by sdispater** [comment]
I agree. And that's something I had in mind since creating a config interactively each time might be cumbersome if you have a lot of projects.

**Comment by sdispater** [comment]
As of version `0.4.0` (just released) you can execute `poet init default` to generate a default `poetry.toml` template.
