### ISSUE TITLE
How does it compare to Pipenv?

### ISSUE THREAD

**Issue by douglas** [sdispater/poet#6]
Hello!

Thanks for writing poet =)

I really liked the usage examples of this tool, but got curious on how it compares with Pipenv:

https://github.com/kennethreitz/pipenv

Sorry if this is an obvious or simple question.

**Comment by sdispater** [comment]
`pipenv` only handles dependencies and eases virtualenv handling but, in the end, to package and publish your package to pypi you will still need to create a `MANIFEST.in`, a `setup.py` file and so on. So, as I see it the `Pipfile` file only replaces the `requirements.txt` which is used by `pip`.

So, `pipenv` only solves part of the problem while `poet` tries to be a all-in-one, intuitive tool to handle the standard Python package and application workflow.

**Comment by douglas** [comment]
Amazing! Thanks for the response! I will try to test it on my projects.

Btw, is it possible to use it on services like Heroku and Travis?

Congrats for the project, this is a much needed improvement to package handling in Python!

**Comment by sdispater** [comment]
On Travis you can have your `install` section look like:

```yaml
install:
  - pip install pip -U  # Make sure you have the latest pip version
  - pip install setuptools -U  # Needed for Python 2.7 builds
  - pip install pypoet
  - poet install
```
