### ISSUE TITLE
Occur HTTPError during publish command

### ISSUE THREAD

**Issue by winterjung** [sdispater/poet#7]
Hello!
I would like to test the features of this project, so have run the following commands in `examples/basic`.
(I Modified package name to `basic-poet` in `poetry.toml`)
```sh
> pip install poet
# after installing
> poet publish
No package found. Building it.

 Building basic-poet (0.1.0)
 Built basic-poet (0.1.0)

  - Created basic-poet-0.1.0.tar.gz

Publishing basic-poet (0.1.0) to pypi
Enter your username: JungWinter
Enter your password:

 - Registering basic-poet-0.1.0.tar.gz
```
I expected the `basic-poet` package to be uploaded on pypi,
but I got a `HTTPError`.

```sh
[HTTPError]                                                                
  410 Client Error: This API is no longer supported, instead simply upload   
  the file. for url: https://upload.pypi.org/legacy/
```

I expect you to know how to solve this problem.

**Comment by sdispater** [comment]
That's strange. Do you have a `~/.pypirc` file? And what is the url specified for pypi?

**Comment by winterjung** [comment]
Thanks for your reply!
I don't have `~./pypirc` on my linux server and same on local window desktop.
Is it necessary to publish on pypi?

And what is "url for pypi"? I didn't set any url about pypi.

**Comment by sdispater** [comment]
Poet uses `twine` internally which uses the `~/.pypirc` file to get information about remote repositories (like username, password and url).

If you don't have a `~/.pypirc` file it will use a default config that seems to fail when registering the package (due to the url being used it seems).

Anyway, this will likely changed in future poet versions to not depend on the `~/.pypirc` file and use its own config file with more sensible defaults.

For now, you could create the `~/.pypirc` file with the following content:

```ini
[distutils]
index-servers =
    pypi

[pypi]
repository: https://pypi.python.org/pypi
username: you-user-name
password: your-password
```

`username` and `password` are optional.

**Comment by winterjung** [comment]
Thanks for the advice.
It solved `410 Client Error`! 👍 

Unfortunately, now I have another error.
```sh
[HTTPError]                                                                                                 
  401 Client Error: You must be identified to edit package information for url: https://pypi.python.org/pypi
```
Do you have any ideas?

\+
```sh
$ cat poetry.toml 
[package]
name = "basic-poet-example"
version = "0.1.0"
description = "Basic example"
license = "MIT"
authors = [
    "jungwinter <wintermy201@naver.com>"
]
readme = "README.rst"
homepage = "https://github.com/sdispater/poet"
keywords = ['packaging', 'poet']
include = ['basic_example/**/*', 'my_module.py']
python = ["^3.5"]

[dependencies]
requests = "^2.13"

[dev-dependencies]
pytest = "^3.0"
```
and
```sh
$ cat ~/.pypirc
[distutils]
index-servers =
    pypi

[pypi]
repository: https://pypi.python.org/pypi
username: jungwinter
```

**Comment by sdispater** [comment]
Do you have an account on pypi? Did you enter the right password?

**Comment by winterjung** [comment]
Oh, I confused my pypi password XD. 
I could solve the problem!
Thanks for helping! 🍰
